version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - dependency
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
